export const USER_AUTH_CHANGED = 'USER_AUTH_CHANGED';
export const PRODUCTS_CHANGED = 'PRODUCTS_CHANGED';
export const MODAL_STATE_CHANGED = 'MODAL_STATE_CHANGED';
export const CATEGORIES_RECEIVED = 'CATEGORIES_RECEIVED';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const BASKET_PRODUCTS_CHANGED = 'BASKET_PRODUCTS_CHANGED';
export const NEW_BASKET_DATA = 'NEW_BASKET_DATA';
